### ISSUE TITLE
Got 'nan' loss when reproducing the results

### ISSUE THREAD

**Issue by Xiaoyu-SZ** [crazyfat/Cbox4cr#1]
Hi, thanks for sharing the code for this exciting work! I tried to reproduce the results but failed in training due to nan loss. Are there suggestions for the problem?

I used the original code in the repo and the given command:

```
python main.py --dataset movielens_100k --save_load_path saved-models/best_movielens_100k.json --threshold 4 --leave_n 1 --keep_n 5 --max_history_length 5 --n_neg_train 1 --n_neg_val_test 100 --training_batch_size 128 --val_test_batch_size 256 --emb_size 64 --lr 0.0005  --tau 0.01 --theta 0.02 --beta 0.4 --activation 'relu' --cen 0.02 --gamma 12.0 --epsilon 2.0 --num_layers 1 --std_vol -2 --u2i True
```

Here is the output of my trial:

```
INFO:model.models:| epoch 1 | 115/1156 batches | ms/batch 65.46 | loss nan |
INFO:model.models:| epoch 1 | 230/1156 batches | ms/batch 8.88 | loss nan |
INFO:model.models:| epoch 1 | 345/1156 batches | ms/batch 8.63 | loss nan |
INFO:model.models:| epoch 1 | 460/1156 batches | ms/batch 8.63 | loss nan |
INFO:model.models:| epoch 1 | 575/1156 batches | ms/batch 8.83 | loss nan |
INFO:model.models:| epoch 1 | 690/1156 batches | ms/batch 8.48 | loss nan |
INFO:model.models:| epoch 1 | 805/1156 batches | ms/batch 22.53 | loss nan |
```

Thanks a lot!

**Comment by crazyfat** [comment]
您好，邮件已收到！

**Comment by crazyfat** [comment]
Thank you for your interest! I speculate that an error occurred due to division by zero during the training process. This might be related to the precision of the graphics card, as there are numerous computations involving values close to zero during the contrastive learning process. These are the graphics cards I used during the experiment: NVIDIA RTX A6000 and NVIDIA RTX 2080Ti.

**Comment by Xiaoyu-SZ** [comment]
I tried adding 1E-12 to the denominator in all '/' (division) operations in the code, but still had the same problem. Then I tried running experiments on 2080Ti and succeed.
So I think the problem is solved, although I'm not sure exactly the cause yet. Thanks very much for your reply :) !
